### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by Seiun-Nebula** [wAIfu-DEV/w-AI-fu#15]
when i open the shortcut to boot up the cmd i get a error for python TTS and python LLM i what should i do and here is a screen shot of the error
![error2](https://github.com/wAIfu-DEV/w-AI-fu/assets/122134297/1caa4b73-5b37-4539-a9e5-de11378cb469)

![error](https://github.com/wAIfu-DEV/w-AI-fu/assets/122134297/d1579ff4-928e-4dd6-88d0-b44ac7e29d26)

**Comment by wAIfu-DEV** [comment]
Hi,
could you try running:
`pip uninstall novelai_api`
then
`pip install novelai_api==0.16.3`

From what I understand, this issue could be caused by an incomplete installation of a package.
https://www.partitionwizard.com/partitionmanager/the-specified-module-could-not-be-found.html

**Comment by Seiun-Nebula** [comment]
that did it thank you

**Comment by wAIfu-DEV** [comment]
Glad to hear that fixed it,
 for the AssignProcess thingy there was an issue already made: https://github.com/wAIfu-DEV/w-AI-fu/issues/7
 Hope it will fix it for you
