### ISSUE TITLE
Critical Error: Could not contact LLM python script after 10s

### ISSUE THREAD

**Issue by MaraSov95** [wAIfu-DEV/w-AI-fu#21]
Hi, excuse me but i have this problem. I already did steps 1 to 4 but when i open the "Run w-AI-fu" shortcut it says this:

Traceback (most recent call last):
  File "C:\Users\sonic\Desktop\w-AI-fu-1.2.2 Vtuber\w-AI-fu\novel\novel_tts.py", line 3, in <module>

python TTS:
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

python LLM:
Traceback (most recent call last):
  File "C:\Users\sonic\Desktop\w-AI-fu-1.2.2 Vtuber\w-AI-fu\novel\novel_llm.py", line 6, in <module>

python LLM:
    from boilerplate import API
  File "C:\Users\sonic\Desktop\w-AI-fu-1.2.2 Vtuber\w-AI-fu\novel\boilerplate.py", line 5, in <module>

python LLM:
    from aiohttp import ClientSession
ModuleNotFoundError: No module named 'aiohttp'

Critical Error: Could not contact LLM python script after 10s

**Comment by wAIfu-DEV** [comment]
The issue seems to be linked to uninstalled python dependencies.

Did you have any errors while running INSTALL.bat ?
if not you could you try running it again until it says "Done." ?

If it still doesn't work you can try installing theme manually by running:
`pip install -r <PATH TO W-AI-FU>\w-AI-fu\install\py_requirements.txt`

**Comment by MaraSov95** [comment]
no, i didn't have any errors while installing it's just when i try to open the app.

**Comment by MaraSov95** [comment]
> The issue seems to be linked to uninstalled python dependencies.
> 
> Did you have any errors while running INSTALL.bat ? if not you could you try running it again until it says "Done." ?
> 
> If it still doesn't work you can try installing theme manually by running: `pip install -r <PATH TO W-AI-FU>\w-AI-fu\install\py_requirements.txt`

could you send me a video on how to do it please? I tried what you said but it still gives me the same error.

**Comment by wAIfu-DEV** [comment]
1 - Go to the directory containing 'py_requirements.txt'
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/132222556/2b83f574-2e41-4902-8014-77ca781baf8f)
2 - Copy the path to the folder
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/132222556/536e52aa-a038-4219-b302-c46b8f5b948e)
3 - Open a command prompt and type this using the path you copied:
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/132222556/7d91825f-0a9b-4721-8ea4-4f54717776f5)

**Comment by MaraSov95** [comment]
> 1 - Go to the directory containing 'py_requirements.txt' ![image](https://user-images.githubusercontent.com/132222556/246858200-2b83f574-2e41-4902-8014-77ca781baf8f.png) 2 - Copy the path to the folder ![image](https://user-images.githubusercontent.com/132222556/246859043-536e52aa-a038-4219-b302-c46b8f5b948e.png) 3 - Open a command prompt and type this using the path you copied: ![image](https://user-images.githubusercontent.com/132222556/246860208-7d91825f-0a9b-4721-8ea4-4f54717776f5.png)

i did that and the installation process was a success but it still says the same thing: that pyaudio and the other dependencies are still missing, do you know why could that be?

**Comment by wAIfu-DEV** [comment]
Honestly I have no idea at this point.

Do you happen to have multiple versions of python installed?
If yes what I could suggest is to uninstall all your versions of python and reinstall.

Other than this I don't know where this issue might be coming from.

**Comment by MaraSov95** [comment]
> Honestly I have no idea at this point.
> 
> Do you happen to have multiple versions of python installed? If yes what I could suggest is to uninstall all your versions of python and reinstall.
> 
> Other than this I don't know where this issue might be coming from.

i only have one version of python installed and is python 3.10.11, could it be that it has something to do with the version i have installed?

**Comment by wAIfu-DEV** [comment]
I don't think so, what's weird about it is that pip has no issue downloading but python somehow has a problem with it.
Might be an issue with one of the two, so I would reinstall personally.

**Comment by MaraSov95** [comment]
> I don't think so, what's weird about it is that pip has no issue downloading but python somehow has a problem with it. Might be an issue with one of the two, so I would reinstall personally.

Thanks for the help, i'll try with different versions of python until it works. I'm sure it will work with one of them.

**Comment by wAIfu-DEV** [comment]
Did resinatlling solve your issue ?

**Comment by wAIfu-DEV** [comment]
Please reopen this issue if this issue if the problem persists.

**Comment by alexvermaning0** [comment]
im not the original issue creator but im also having the issue.
i have python 3.10.10 and node 20.9.0
if i launch the python files that use pyaudio i don't get the message pyaudio is missing but when i run via nodejs it does.
