### ISSUE TITLE
Error: Received incorrect json from TTS.

### ISSUE THREAD

**Issue by answerecho** [wAIfu-DEV/w-AI-fu#24]
I tried to change the audio outputs but now I get no sound and it keeps giving me this 500 Internal Server Error when I load the program. I tried going back to the default sound devices but I get this error regardless of what sound devices I choose. I also tried running install.bat and cmd install py requirements.txt 
Here are the results from running in test:

Entering TEST mode ...
Checking LLM response ...
Closed LLM.
passed.
Checking TTS response ...
Error: Received incorrect json from TTS.
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Closed TTS.
passed.
Checking CHAT response ...
Closed CHAT.
passed.
Checking Text Input ...
passed.
Checking Voice Input ...
passed.
Successfuly passed all tests.
Killing subprocesses ...
Exiting w.AI.fu
Press any key to continue . . .

**Comment by answerecho** [comment]
I checked the other error that was closed like this but I'm using a paid account and the credentials are correct, I guess I'll try a new oauth token if I can in the meantime

**Comment by wAIfu-DEV** [comment]
Sorry to hear you are having an issue with the program.

The oauth token shouldn't be the issue since it is linked to Twitch and not NovelAI.
The issue comes from the python script responsible for NovelAI's TTS.

Since the problem started when you changed the audio output could you try going into the config.json file and change these parameters: "audio_device" & "audio_device_other" to -1 ?
It should at least allow you to show the UI again.

When running the app using run.bat, does it show any other error message ?

**Comment by answerecho** [comment]
No problem, I'm just grateful to use this program so thank you for responding
I changed those parameters to -1, the llm seems to work fine but I still get the same message which leads to an eventual python script error kicking me from the program: 

Error: Received incorrect json from TTS.
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Reinitializing ...
Getting audio devices ...
Loaded LLM.
Loaded TTS.
lol
Critical Error: Could not contact CHAT python script after 10s
Killing subprocesses ...
Exiting w.AI.fu
Press any key to continue . . .

**Comment by wAIfu-DEV** [comment]
I'm actually confused as to why this error pops up.
Just out of curiosity, which version of w-AI-fu are you using?

**Comment by answerecho** [comment]
I'm using 1.2.2

**Comment by answerecho** [comment]
Oh! I restarted and it works now
