### ISSUE TITLE
AssignProcessToJobObject: (87) The parameter is incorrect.

### ISSUE THREAD

**Issue by goenyan** [wAIfu-DEV/w-AI-fu#25]
The issue caused when I run the program.
And this one is command prompt error
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/26736922/956b5be5-3f63-423d-865f-f2350f9d6c1d)

If I run the shortcut with administrator, it will be like this.
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/26736922/b0e0d5a5-bd07-46b9-a8f1-3fcff0dffa69)

Seem like the run.bat see the node app.js is in system32 but it not.

P/S: I have checked the main.js file
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/26736922/9e748b6e-ebdd-47bf-9978-5149b886c597)

I have NodeJs 20.3.1 and Python 3.10.11 installed

**Comment by wAIfu-DEV** [comment]
Hi this is an issue linked to this: https://github.com/wAIfu-DEV/w-AI-fu/issues/7

It seems that the only way to make it work is to run the application 2 times.

**Comment by wAIfu-DEV** [comment]
Hope this helps

**Comment by goenyan** [comment]
Thank you, it working.
Btw how do I made the subtitle break line or limited it to readable area like in your video?
I'm using Streamlabs to stream.
And can I add your Discord?

**Comment by wAIfu-DEV** [comment]
w-AI-fu_dev#0678

You need to activate "Use custom extents" in the text source and then activate "Wrap". 
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/132222556/bc844e39-b86f-4e95-bb63-618b72efe437)
