### ISSUE TITLE
update error?

### ISSUE THREAD

**Issue by newbornpowersource** [wAIfu-DEV/w-AI-fu#29]
Im trying to update from 1.2.2. to 1.2.6 but I run into a loop. update completes and replaces files, but always updates to 1.2.5 instead. each time i run

result: run > update to 1.2.6? > y > update complete > run shortcut > you are on 1.2.5 , upgrade to 1.2.6? > y > update complete > run shortcut > you are on 1.2.5, upgrade to 1.2.6? > y > update complete > (repeat)

I have tried downloading the zip directly and trying a fresh install but I still get to the same result as above. any suggestions? :/

(BTW LOVE THE PROJECT!)

**Comment by newbornpowersource** [comment]
> Happens to me also, i think he just forgot to change the version number in the config or something, as a workaround for now you can just type N for no and it will load the program as usual

i see lol okay will proceed to ignore it until fixed.

**Comment by wAIfu-DEV** [comment]
yeah forgot to change the version number sorry about that

**Comment by wAIfu-DEV** [comment]
changed the files of the 1.2.6 update it should work after update now.
