### ISSUE TITLE
TypeError: cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by MaraSov95** [wAIfu-DEV/w-AI-fu#32]
![Screenshot (7167)](https://github.com/wAIfu-DEV/w-AI-fu/assets/137000071/5aa57743-de56-41d4-ae0c-44a3514b1b04)

hi, hey i have an error, when i type in the Twitch Chat it closes the program saying this: TypeError: cannot read properties of undefined (reading '0') and i already added my Twitch Name, Oauth and all the other stuff necessary but it still closes the app when i type something in the Twitch Chat.

**Comment by Flashisepic** [comment]
I'm having the almost the same issue, I put in the correct info and even have a twitch dev app cli id. and I still cannot get it to read the chat or respond to me in chat without the same error as above.

**Comment by wAIfu-DEV** [comment]
I'm sorry you're having an issue with w-AI-fu.
Does the issue appear when you start the app or when you receive a new message ?

**Comment by wAIfu-DEV** [comment]
Ok I managed to reproduce the issue, it seems that the websocket for twitch chat messages sends the channel name in full lowercases, so If your channel name was (for ex.) TestChannelName then the regular expression would not match and lead would to the error.

So for a temporary fix just put your channel name in the Accounts section in lower case and it should be good.
Real fix coming soon™️

**Comment by wAIfu-DEV** [comment]
didn't get the error myself since my channel name is already lowercase lol
