### ISSUE TITLE
Implement a needs system similar  to The Sims

### ISSUE THREAD

**Issue by rpfilomeno** [wAIfu-DEV/w-AI-fu#36]
Implement a needs system similar  to The Sims https://www.youtube.com/watch?v=9gf2MT-IOsg
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/5754735/55c08200-92b2-4f47-8293-f5daf965b300)

**Comment by wAIfu-DEV** [comment]
NovelAI doesn't handle specific instructions like those.
While this won't work on this version, I am currently in the process of making a rewrite of w-AI-fu that would allow the use of openai models instead of novelai ones.
