### ISSUE TITLE
Python LLM and TTS issues

### ISSUE THREAD

**Issue by wAIfu-DEV** [wAIfu-DEV/w-AI-fu#44]
### Discussed in https://github.com/wAIfu-DEV/w-AI-fu/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **SpnkThe** October  3, 2023</sup>
Hello, so i have a small issue with setting up this program.
After successful installation of nodejs and python dependencies with `install.bat`, `run.bat` file gives out a error:

```
w-AI-fu 1.2.9
Loading config informations ...
Loading character "Hilda" ...
Loading filter ...
Getting audio devices ...
Spawning subprocesses ...
python LLM:
Traceback (most recent call last):
  File "C:\Users\jarek\Desktop\w-AI-fu main\w-AI-fu\novel\novel_llm.py", line 17, in <module>

python LLM:
    from flask import Flask, request, jsonify
  File "C:\Users\jarek\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "C:\Users\jarek\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (C:\Users\jarek\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\urls.py)

python TTS:
Traceback (most recent call last):
  File "C:\Users\jarek\Desktop\w-AI-fu main\w-AI-fu\novel\novel_tts.py", line 10, in <module>

python TTS:
    from flask import Flask, request, jsonify, make_response
  File "C:\Users\jarek\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\__init__.py", line 5, in <module>

python TTS:
    from .app import Flask as Flask
  File "C:\Users\jarek\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (C:\Users\jarek\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\urls.py)

Critical Error: Could not contact LLM python script after 10s
Killing subprocesses ...
Exiting w.AI.fu
Press any key to continue . . .
```
It's my first time being face to face with coding and at this point i have no clue how this could be fixed, any help?
My current python version is 3.11.4 (but i had same error on recomended 3.10.10 version which i deleted entirely)
My nodeJS version is  19.8.1

</div>

**Comment by wAIfu-DEV** [comment]
Hello, sorry to hear you are having issues with the program,
I never encountered this bug before, so I'll do some tests to see if it is global or happening or rarer cases.

In the meantime, I can direct you towards [w-AI-fu V2](https://github.com/wAIfu-DEV/w-AI-fu_v2) it is a complete rewrite of w-AI-fu. While it is still technically in beta, the program is a lot more stable than the version you are using and does not make use of Flask, which is what seems to be causing the issue on your end.

Hope this helps.

**Comment by wtfVIKAS** [comment]
i got the same error help plz
