### ISSUE TITLE
Python 3.12 (and later) support

### ISSUE THREAD

**Issue by LarsDuJour** [wAIfu-DEV/w-AI-fu#54]
Hi, currently w-AI-fu has several dependencies that require Python 3.11 or less.

Is there any timeline or interest in updating these dependencies?

Sincerly, Lars

**Comment by wAIfu-DEV** [comment]
Hi, there are no plans to update anything related to this specific repo as long as it's not something that is horribly broken, all development time and resources are towards [w-AI-fu_v2](https://github.com/wAIfu-DEV/w-AI-fu_v2).
