### ISSUE TITLE
Error: Received incorrect json from LLM

### ISSUE THREAD

**Issue by Rebvilion** [wAIfu-DEV/w-AI-fu#56]
Hello everyone! 
I have a problem with Novel AI, I specify the correct login information, as a result there is no response from the server, I created another account, such a problem.
What could be the reason?
![2024-06-08_17-07-26](https://github.com/wAIfu-DEV/w-AI-fu/assets/171734287/916327cf-b938-4196-905a-0995b35b6db6)

**Comment by Rebvilion** [comment]
When trying to test the audio device, the same error 
![2024-06-08_18-27-44](https://github.com/wAIfu-DEV/w-AI-fu/assets/171734287/77f88696-8c78-479d-87ac-9b611d305e6a)

**Comment by xxandeer** [comment]
Well, you dont get the correct response from NovelAI. 500 is often a problem on the server end. Can you manually make an api req and get a correct payload return?

**Comment by Rebvilion** [comment]
> Well, you dont get the correct response from NovelAI. 500 is often a problem on the server end. Can you manually make an api req and get a correct payload return?

Can you tell me please how to do it

**Comment by LexiconAlex** [comment]
In sure that you can find esay examples in their docs. And you can use postman, bruno etc. to try the api reqs

**Comment by xxandeer** [comment]
In sure that you can find esay examples in their docs. And you can use
postman, bruno etc. to try the api reqs


lör 8 juni 2024 kl. 13:33 skrev LexiconAlex ***@***.***>:
