### ISSUE TITLE
Contuined Critical Error: Received incorrect json from LLM issue

### ISSUE THREAD

**Issue by Chrustos** [wAIfu-DEV/w-AI-fu#6]
So i was able to get it working, and i had connected the twitch integration, and upon chat typing i received 
Critical Error: Received incorrect json from LLM.
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

When reloaded, it will keep showing this with the same error, unable to use afterwards

**Comment by wAIfu-DEV** [comment]
Hi, I just published a new release to display more insightful error messages.
This won't fix youre issue but will help to understand where it comes from so that we can fix it.

To update: Just open the application, and type Y when asked if you want to update.

**Comment by Chrustos** [comment]
awesome, i just booted it up and typed and the the account wasn't entered properly, i had the right email. but i use a lower case first letter and it accepted it, but i got this. I assuming that this mean the account was used up as it was free 

409 - Not eligible for this model.

Critical Error: Received incorrect json from LLM.

Then i used a new account and it worked fine 
Just did a test stream, and she worked till this came up

402 - Anonymous quota reached.
Witch im guessing this means that the free account has reached its limit

**Comment by Chrustos** [comment]
also shortly after it came up again with 
 409 - Not eligible for this model.

Critical Error: Received incorrect json from LLM.
And then errored

**Comment by wAIfu-DEV** [comment]
The issue of twitch chat reading turning off after a config change should be fixed in the next release, I managed to find the issue while testing live.

I'm interested to know if the "409 - Not eligible for this model." appeared from the get-go or if it appeared after a certain amount of time? The model used is Euterpe which should be usable by every tier.

Please update me if you have any more issues, I'll poste here when the realease is ready.

**Comment by wAIfu-DEV** [comment]
Release is live

**Comment by wAIfu-DEV** [comment]
Watched your test stream, I noticed the answers were quite short.
If you want to have longer answers I suggest bumping up the craziness and creativity, and making sure her answers in the  example dialogue are long as well.

**Comment by wAIfu-DEV** [comment]
Here is what it is capable of: https://www.youtube.com/watch?v=oFBLl9C2VrE&t=5s
#AD
