### ISSUE TITLE
AssignProcessToJobObject: (87) The parameter is incorrect.

### ISSUE THREAD

**Issue by Yoishima** [wAIfu-DEV/w-AI-fu#7]
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/133375618/a94d564f-c483-4dc9-baa6-3da6981441e4)

this happens whenever i open run.bat

![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/133375618/230d1344-2d9f-440b-84f8-b80128ba719b)

and here's when i open test.bat

**Comment by xxandeer** [comment]
You have to enter you username (email) and password for NovelAI in the correct files.
w-AI-fu main\UserData\auth novel_user.txt and novel_pass.txt

**Comment by Yoishima** [comment]
> You have to enter you username (email) and password for NovelAI in the correct files. w-AI-fu main\UserData\auth novel_user.txt and novel_pass.txt

same errors showed up after doing so

**Comment by wAIfu-DEV** [comment]
Hi, sorry you're having trouble with the program.

Does the web page for the control panel show up before it crashes?
If not then the way the .html file is opened might be at fault

**Comment by Yoishima** [comment]
> Hi, sorry you're having trouble with the program.
> 
> Does the web page for the control panel show up before it crashes? If not then the way the .html file is opened might be at fault

it does open, after a few sec it'll show a popup saying application is closed. which would then i'll press ok

**Comment by wAIfu-DEV** [comment]
There might be an issue with NodeJS's exec() function considering the timing and what I have read online.
I'll try finding a workaround and publish it ASAP.
I'll hit you up when it's done.

**Comment by Yoishima** [comment]
i did another test.bat and everything passed without errors, the only problem now is the assigntoprocesstojobobject (87)

**Comment by Yoishima** [comment]
so, opened a 2nd run.bat while the 1st run.bat is active and showing the error, the 2nd run.bat opened without issues 

![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/133375618/2af535c2-f030-46c6-baee-aa2ab1e9b72c)

**Comment by wAIfu-DEV** [comment]
Update is live, to update just run w-AI-fu and accept the update.
Tell me if it solved your issue.

**Comment by Yoishima** [comment]
still showing the assignProcessToJobObject, but when i open another run.bat while the first one is opened, it works, kinda weird as i'll have to open run.bat 2 times for it to work

**Comment by wAIfu-DEV** [comment]
Since it is somewhat working, I'll close the issue.
From what I am getting from this article, it might be cause by system error or conflict, so not something I'll be able to solve.
https://appuals.com/fix-error-87-the-parameter-is-incorrect/

IF you encounter any other bug, I'd be grateful if you could open a new issue.
