### ISSUE TITLE
AI keep repeating the greeting 

### ISSUE THREAD

**Issue by vornthorn** [wAIfu-DEV/w-AI-fu#8]
the AI kept repeating the greeting message for every question (see a an example convo attached)
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/114248512/7e4079dd-0624-4ec5-918f-28e4449f8a8a)

**Comment by wAIfu-DEV** [comment]
Hi, sorry to hear you're having problems with the program.

From what I can see with your screenshot, the AI is not repeating the exact same message every time, which leads me to think there might be an issue with how the character is defined.

Could you send me a screenshot of the character sheet in the control panel ?
If you don't want to make it public, you can send it via discord: w-AI-fu_dev#0678

**Comment by vornthorn** [comment]
I retest it again after adjusting the craziness and creativity it stopped repeating as you can see.
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/114248512/c183677b-c6a8-48f8-a701-a498c4c7e01f)
![image](https://github.com/wAIfu-DEV/w-AI-fu/assets/114248512/ce8c4270-617f-43d7-afbe-d9336c3860ed)
I guess it was just character setting as you said

**Comment by wAIfu-DEV** [comment]
Glad to hear you could make it work !

Does the python error you're getting affect the usage of the program ?

**Comment by vornthorn** [comment]
no just appears on the logs and on the webpage but the AI or TTS  works just fine, it seem to be unaffected by the error I guess

**Comment by wAIfu-DEV** [comment]
Weird...
It's affecting both the LLM and TTS script so it might be an issue with python itself ?

Anyway, I'll close this issue since your problem has been solved.
If you encounter any other bug, I'd be grateful if you could open a new issue :)
